"""
Django settings for fitness_center project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')
load_dotenv(BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-dev-only-change-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'workouts',
    'trainers',
    'memberships',
    'tailwind',
    'theme',
    # 'debug_toolbar',  # Отключаем Debug Toolbar
]

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',  # Отключаем Debug Toolbar
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'fitness_center.urls.AdminAccessMiddleware',  # Middleware для защиты админки
]

ROOT_URLCONF = 'fitness_center.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Настройки кэширования шаблонов - закомментируем, чтобы избежать конфликта
# TEMPLATES[0]['OPTIONS']['loaders'] = [
#     ('django.template.loaders.cached.Loader', [
#         'django.template.loaders.filesystem.Loader',
#         'django.template.loaders.app_directories.Loader',
#     ]),
# ]

WSGI_APPLICATION = 'fitness_center.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # Оптимизация SQLite для более быстрой работы
            'timeout': 20,  # Увеличиваем таймаут для предотвращения блокировок
            'isolation_level': None,  # Отключаем изоляцию для повышения производительности
            'cached_statements': 1000,  # Увеличиваем кэш SQL-запросов
        }
    }
}

# Настройки кэширования
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-fitness-center',
        'TIMEOUT': 300,  # 5 минут
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Максимальное количество элементов в кэше
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Пользовательская модель
AUTH_USER_MODEL = 'users.CustomUser'

# URL для входа в систему
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/account/'

# Email настройки (для уведомлений)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Для разработки

# Настройки безопасности
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'

# Путь к npm для django-tailwind (Windows / macOS / Linux)
import shutil
NPM_BIN_PATH = shutil.which("npm") or "npm"

# Summernote настройки
SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '300px',
        'toolbar': [
            ['font', ['bold', 'italic']],
        ],
        'styleTags': ['p'],
        'disable_upload': True,
        'fontNames': ['Roboto'],
        'fontNamesIgnoreCheck': ['Roboto'],
    },
    'disable_attachment': True,
    'use_jquery': True,
    'iframe': True,
    'empty': {
        'iframe': True,
    },
    'css': (
        '/static/admin/css/summernote-roboto.css',
    ),
}

# Настройки для Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

# Отключаем панель отладки на главной странице
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: request.path.startswith('/admin/') or 
                                           request.path.startswith('/users/') or
                                           'debug' in request.GET,
}
