# Generated by Django 5.2 on 2025-04-24 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='WorkoutDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='workout_directions/', verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='workouts.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'направление тренировок',
                'verbose_name_plural': 'направления тренировок',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('start_time', models.TimeField(verbose_name='время начала')),
                ('end_time', models.TimeField(verbose_name='время окончания')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='максимальное количество участников')),
                ('participants', models.ManyToManyField(blank=True, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='trainers.trainer', verbose_name='тренер')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.workoutdirection', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'тренировка',
                'verbose_name_plural': 'тренировки',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
