# Generated by Django 5.2 on 2025-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workoutdirection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'цель тренировки',
                'verbose_name_plural': 'цели тренировок',
            },
        ),
        migrations.AddField(
            model_name='workoutdirection',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='directions', to='workouts.traininggoal', verbose_name='цели тренировки'),
        ),
    ]
