# Generated by Django 5.2 on 2025-04-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_traininggoal_workoutdirection_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdirection',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
