# Generated by Django 5.2 on 2025-05-19 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainer_description'),
        ('workouts', '0005_remove_workoutdirection_category_delete_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['date', 'time'], 'verbose_name': 'тренировка', 'verbose_name_plural': 'тренировки'},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='start_time',
        ),
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='длительность (минуты)'),
        ),
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.TimeField(default='12:00', verbose_name='время'),
        ),
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='max_participants',
            field=models.IntegerField(verbose_name='максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='trainers.trainer'),
        ),
        migrations.CreateModel(
            name='WorkoutRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_registrations', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'запись на тренировку',
                'verbose_name_plural': 'записи на тренировки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'workout')},
            },
        ),
    ]
