# Generated by Django 5.2 on 2025-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workout_options_remove_workout_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(verbose_name='длительность (минуты)'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='workoutregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата записи'),
        ),
    ]
