# Generated by Django 5.2 on 2025-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_workout_created_at_alter_workout_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='hall',
            field=models.CharField(choices=[('small', 'Малый зал'), ('large', 'Большой зал')], default='small', max_length=10, verbose_name='зал'),
        ),
    ]
