# Generated by Django 5.2 on 2025-04-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('duration', models.PositiveIntegerField(verbose_name='срок действия (в днях)')),
            ],
            options={
                'verbose_name': 'абонемент',
                'verbose_name_plural': 'абонементы',
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='статус')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='memberships.membership', verbose_name='абонемент')),
            ],
            options={
                'verbose_name': 'заявка на абонемент',
                'verbose_name_plural': 'заявки на абонементы',
                'ordering': ['-created_at'],
            },
        ),
    ]
