# Generated by Django 5.2 on 2025-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для карточки абонемента', null=True, upload_to='memberships/', verbose_name='изображение'),
        ),
    ]
