# Generated by Django 5.2 on 2025-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membership_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(help_text='Используйте панель инструментов для форматирования текста: жирный текст, курсив, списки и другие элементы форматирования.', verbose_name='описание'),
        ),
    ]
