# Generated by Django 5.2 on 2025-04-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_membership_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(blank=True, help_text='Используйте HTML-теги для форматирования текста: <b>жирный текст</b>, <i>курсив</i>', null=True, verbose_name='описание'),
        ),
    ]
