# Generated by Django 5.2 on 2025-05-22 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата отправки')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.userrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сообщение чата',
                'verbose_name_plural': 'сообщения чата',
                'ordering': ['created_at'],
            },
        ),
    ]
