# Generated by Django 5.2 on 2025-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('photo', models.ImageField(upload_to='trainers/', verbose_name='фото')),
                ('specialization', models.CharField(max_length=200, verbose_name='специализация')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'тренеры',
            },
        ),
    ]
